name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  TF_IN_AUTOMATION: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::454449944634:role/GitHubOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Set artifact name
        id: names
        run: echo "zip=lambda_$(date +'%Y%m%d%H%M%S').zip" >> $GITHUB_OUTPUT

      - name: Build Lambda package
        working-directory: app
        run: |
          pip install -r requirements.txt -t package
          cp -r *.py package/
          cd package
          zip -r ../${{ steps.names.outputs.zip }} .
          ls -lh ../${{ steps.names.outputs.zip }}

      - name: Get artifact bucket
        id: tf_output
        working-directory: infra
        run: echo "bucket=$(terraform output -raw artifact_bucket)" >> $GITHUB_OUTPUT


      - name: Upload artifact to S3
        run: aws s3 cp app/${{ steps.names.outputs.zip }} s3://${{ steps.tf_output.outputs.bucket }}/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init/plan/apply
        working-directory: infra
        run: |
          terraform init
          terraform apply -auto-approve \
            -var "artifact_key=${{ steps.names.outputs.zip }}"